# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpcdemo.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='grpcdemo.proto',
  package='grpcdemopb',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0egrpcdemo.proto\x12\ngrpcdemopb\"\x07\n\x05\x45mpty\"0\n\x10UnaryFuncRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0e\n\x06height\x18\x02 \x01(\x03\" \n\x11UnaryFuncResponse\x12\x0b\n\x03msg\x18\x01 \x01(\t2\x8d\x01\n\x08GrpcDemo\x12\x35\n\x0bNoParamFunc\x12\x11.grpcdemopb.Empty\x1a\x11.grpcdemopb.Empty\"\x00\x12J\n\tUnaryFunc\x12\x1c.grpcdemopb.UnaryFuncRequest\x1a\x1d.grpcdemopb.UnaryFuncResponse\"\x00\x62\x06proto3'
)




_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='grpcdemopb.Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=37,
)


_UNARYFUNCREQUEST = _descriptor.Descriptor(
  name='UnaryFuncRequest',
  full_name='grpcdemopb.UnaryFuncRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='grpcdemopb.UnaryFuncRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='height', full_name='grpcdemopb.UnaryFuncRequest.height', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=39,
  serialized_end=87,
)


_UNARYFUNCRESPONSE = _descriptor.Descriptor(
  name='UnaryFuncResponse',
  full_name='grpcdemopb.UnaryFuncResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='msg', full_name='grpcdemopb.UnaryFuncResponse.msg', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=89,
  serialized_end=121,
)

DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
DESCRIPTOR.message_types_by_name['UnaryFuncRequest'] = _UNARYFUNCREQUEST
DESCRIPTOR.message_types_by_name['UnaryFuncResponse'] = _UNARYFUNCRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'grpcdemo_pb2'
  # @@protoc_insertion_point(class_scope:grpcdemopb.Empty)
  })
_sym_db.RegisterMessage(Empty)

UnaryFuncRequest = _reflection.GeneratedProtocolMessageType('UnaryFuncRequest', (_message.Message,), {
  'DESCRIPTOR' : _UNARYFUNCREQUEST,
  '__module__' : 'grpcdemo_pb2'
  # @@protoc_insertion_point(class_scope:grpcdemopb.UnaryFuncRequest)
  })
_sym_db.RegisterMessage(UnaryFuncRequest)

UnaryFuncResponse = _reflection.GeneratedProtocolMessageType('UnaryFuncResponse', (_message.Message,), {
  'DESCRIPTOR' : _UNARYFUNCRESPONSE,
  '__module__' : 'grpcdemo_pb2'
  # @@protoc_insertion_point(class_scope:grpcdemopb.UnaryFuncResponse)
  })
_sym_db.RegisterMessage(UnaryFuncResponse)



_GRPCDEMO = _descriptor.ServiceDescriptor(
  name='GrpcDemo',
  full_name='grpcdemopb.GrpcDemo',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=124,
  serialized_end=265,
  methods=[
  _descriptor.MethodDescriptor(
    name='NoParamFunc',
    full_name='grpcdemopb.GrpcDemo.NoParamFunc',
    index=0,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='UnaryFunc',
    full_name='grpcdemopb.GrpcDemo.UnaryFunc',
    index=1,
    containing_service=None,
    input_type=_UNARYFUNCREQUEST,
    output_type=_UNARYFUNCRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_GRPCDEMO)

DESCRIPTOR.services_by_name['GrpcDemo'] = _GRPCDEMO

# @@protoc_insertion_point(module_scope)
