// Code generated by protoc-gen-go. DO NOT EDIT.
// source: grpcdemo.proto

package grpcdemopb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_9fbeaf5fd8369486, []int{0}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type UnaryFuncRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Height               int64    `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnaryFuncRequest) Reset()         { *m = UnaryFuncRequest{} }
func (m *UnaryFuncRequest) String() string { return proto.CompactTextString(m) }
func (*UnaryFuncRequest) ProtoMessage()    {}
func (*UnaryFuncRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9fbeaf5fd8369486, []int{1}
}

func (m *UnaryFuncRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnaryFuncRequest.Unmarshal(m, b)
}
func (m *UnaryFuncRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnaryFuncRequest.Marshal(b, m, deterministic)
}
func (m *UnaryFuncRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnaryFuncRequest.Merge(m, src)
}
func (m *UnaryFuncRequest) XXX_Size() int {
	return xxx_messageInfo_UnaryFuncRequest.Size(m)
}
func (m *UnaryFuncRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UnaryFuncRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UnaryFuncRequest proto.InternalMessageInfo

func (m *UnaryFuncRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UnaryFuncRequest) GetHeight() int64 {
	if m != nil {
		return m.Height
	}
	return 0
}

type UnaryFuncResponse struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnaryFuncResponse) Reset()         { *m = UnaryFuncResponse{} }
func (m *UnaryFuncResponse) String() string { return proto.CompactTextString(m) }
func (*UnaryFuncResponse) ProtoMessage()    {}
func (*UnaryFuncResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9fbeaf5fd8369486, []int{2}
}

func (m *UnaryFuncResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnaryFuncResponse.Unmarshal(m, b)
}
func (m *UnaryFuncResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnaryFuncResponse.Marshal(b, m, deterministic)
}
func (m *UnaryFuncResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnaryFuncResponse.Merge(m, src)
}
func (m *UnaryFuncResponse) XXX_Size() int {
	return xxx_messageInfo_UnaryFuncResponse.Size(m)
}
func (m *UnaryFuncResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UnaryFuncResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UnaryFuncResponse proto.InternalMessageInfo

func (m *UnaryFuncResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto.RegisterType((*Empty)(nil), "grpcdemopb.Empty")
	proto.RegisterType((*UnaryFuncRequest)(nil), "grpcdemopb.UnaryFuncRequest")
	proto.RegisterType((*UnaryFuncResponse)(nil), "grpcdemopb.UnaryFuncResponse")
}

func init() { proto.RegisterFile("grpcdemo.proto", fileDescriptor_9fbeaf5fd8369486) }

var fileDescriptor_9fbeaf5fd8369486 = []byte{
	// 199 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4b, 0x2f, 0x2a, 0x48,
	0x4e, 0x49, 0xcd, 0xcd, 0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x82, 0xf1, 0x0b, 0x92,
	0x94, 0xd8, 0xb9, 0x58, 0x5d, 0x73, 0x0b, 0x4a, 0x2a, 0x95, 0xec, 0xb8, 0x04, 0x42, 0xf3, 0x12,
	0x8b, 0x2a, 0xdd, 0x4a, 0xf3, 0x92, 0x83, 0x52, 0x0b, 0x4b, 0x53, 0x8b, 0x4b, 0x84, 0x84, 0xb8,
	0x58, 0xf2, 0x12, 0x73, 0x53, 0x25, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0xc0, 0x6c, 0x21, 0x31,
	0x2e, 0xb6, 0x8c, 0xd4, 0xcc, 0xf4, 0x8c, 0x12, 0x09, 0x26, 0x05, 0x46, 0x0d, 0xe6, 0x20, 0x28,
	0x4f, 0x49, 0x95, 0x4b, 0x10, 0x49, 0x7f, 0x71, 0x41, 0x7e, 0x5e, 0x71, 0xaa, 0x90, 0x00, 0x17,
	0x73, 0x6e, 0x71, 0x3a, 0x54, 0x3f, 0x88, 0x69, 0xd4, 0xcb, 0xc8, 0xc5, 0xe1, 0x5e, 0x54, 0x90,
	0xec, 0x92, 0x9a, 0x9b, 0x2f, 0x64, 0xca, 0xc5, 0xed, 0x97, 0x1f, 0x90, 0x58, 0x94, 0x98, 0x0b,
	0xd2, 0x25, 0x24, 0xa8, 0x87, 0x70, 0x98, 0x1e, 0xd8, 0x55, 0x52, 0x98, 0x42, 0x4a, 0x0c, 0x42,
	0x5e, 0x5c, 0x9c, 0x70, 0xab, 0x84, 0x64, 0x90, 0x55, 0xa0, 0xfb, 0x40, 0x4a, 0x16, 0x87, 0x2c,
	0xc4, 0x7d, 0x4a, 0x0c, 0x49, 0x6c, 0xe0, 0x20, 0x31, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0xaf,
	0xae, 0x52, 0xf9, 0x24, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GrpcDemoClient is the client API for GrpcDemo service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GrpcDemoClient interface {
	NoParamFunc(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
	UnaryFunc(ctx context.Context, in *UnaryFuncRequest, opts ...grpc.CallOption) (*UnaryFuncResponse, error)
}

type grpcDemoClient struct {
	cc *grpc.ClientConn
}

func NewGrpcDemoClient(cc *grpc.ClientConn) GrpcDemoClient {
	return &grpcDemoClient{cc}
}

func (c *grpcDemoClient) NoParamFunc(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/grpcdemopb.GrpcDemo/NoParamFunc", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grpcDemoClient) UnaryFunc(ctx context.Context, in *UnaryFuncRequest, opts ...grpc.CallOption) (*UnaryFuncResponse, error) {
	out := new(UnaryFuncResponse)
	err := c.cc.Invoke(ctx, "/grpcdemopb.GrpcDemo/UnaryFunc", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GrpcDemoServer is the server API for GrpcDemo service.
type GrpcDemoServer interface {
	NoParamFunc(context.Context, *Empty) (*Empty, error)
	UnaryFunc(context.Context, *UnaryFuncRequest) (*UnaryFuncResponse, error)
}

// UnimplementedGrpcDemoServer can be embedded to have forward compatible implementations.
type UnimplementedGrpcDemoServer struct {
}

func (*UnimplementedGrpcDemoServer) NoParamFunc(ctx context.Context, req *Empty) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NoParamFunc not implemented")
}
func (*UnimplementedGrpcDemoServer) UnaryFunc(ctx context.Context, req *UnaryFuncRequest) (*UnaryFuncResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnaryFunc not implemented")
}

func RegisterGrpcDemoServer(s *grpc.Server, srv GrpcDemoServer) {
	s.RegisterService(&_GrpcDemo_serviceDesc, srv)
}

func _GrpcDemo_NoParamFunc_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrpcDemoServer).NoParamFunc(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpcdemopb.GrpcDemo/NoParamFunc",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrpcDemoServer).NoParamFunc(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _GrpcDemo_UnaryFunc_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnaryFuncRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrpcDemoServer).UnaryFunc(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpcdemopb.GrpcDemo/UnaryFunc",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrpcDemoServer).UnaryFunc(ctx, req.(*UnaryFuncRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _GrpcDemo_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpcdemopb.GrpcDemo",
	HandlerType: (*GrpcDemoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NoParamFunc",
			Handler:    _GrpcDemo_NoParamFunc_Handler,
		},
		{
			MethodName: "UnaryFunc",
			Handler:    _GrpcDemo_UnaryFunc_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpcdemo.proto",
}
